/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import javax.swing.JOptionPane;

/**
 *
 * @author sistemas
 */
public class TelaFinanceiro extends javax.swing.JFrame {

    /**
     * Creates new form Financeiro
     */
    public TelaFinanceiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTopoTela_Financeiro = new javax.swing.JLabel();
        jLabelInformeTela_Financieiro = new javax.swing.JLabel();
        jLabelLogoTela_Financeiro = new javax.swing.JLabel();
        FundoTopoTela_Financeiro = new javax.swing.JLabel();
        jLabelMatriculaTela_Financeiro = new javax.swing.JLabel();
        jTextFieldMatriculaTela_Financeiro = new javax.swing.JTextField();
        jTextFieldNomeTela_Financeiro = new javax.swing.JTextField();
        jTextFieldEmailTela_Financeiro = new javax.swing.JTextField();
        jTextFieldTelefoneTela_Financeiro = new javax.swing.JTextField();
        jTextFieldEnviarTela_Financeiro = new javax.swing.JTextField();
        jButtonEnviarTela_Financeiro = new javax.swing.JButton();
        jButtonEditarTela_Financeiro = new javax.swing.JButton();
        jButtonSairTela_Financeiro = new javax.swing.JButton();
        jButtonVoltarDaTelaFinanceiro = new javax.swing.JButton();
        jLabelNomeTela_Financeiro = new javax.swing.JLabel();
        jLabelEmailTela_Financeiro = new javax.swing.JLabel();
        jLabelTelefoneTela_Financeiro = new javax.swing.JLabel();
        jLabelAssuntoTela_Financeiro = new javax.swing.JLabel();
        jLabelFundoTela_Financeiro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTopoTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelTopoTela_Financeiro.setForeground(new java.awt.Color(0, 204, 204));
        jLabelTopoTela_Financeiro.setText("FINANCEIRO");
        getContentPane().add(jLabelTopoTela_Financeiro);
        jLabelTopoTela_Financeiro.setBounds(340, 20, 270, 40);

        jLabelInformeTela_Financieiro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInformeTela_Financieiro.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelInformeTela_Financieiro.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInformeTela_Financieiro.setText("PREENCHA O FORMULÁRIO E ENVIE!");
        getContentPane().add(jLabelInformeTela_Financieiro);
        jLabelInformeTela_Financieiro.setBounds(80, 100, 510, 50);

        jLabelLogoTela_Financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Figura2.png"))); // NOI18N
        getContentPane().add(jLabelLogoTela_Financeiro);
        jLabelLogoTela_Financeiro.setBounds(0, 0, 80, 90);

        FundoTopoTela_Financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Topo de telas.png"))); // NOI18N
        getContentPane().add(FundoTopoTela_Financeiro);
        FundoTopoTela_Financeiro.setBounds(0, 0, 600, 100);

        jLabelMatriculaTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelMatriculaTela_Financeiro.setForeground(new java.awt.Color(204, 255, 204));
        jLabelMatriculaTela_Financeiro.setText("Matrícula:");
        getContentPane().add(jLabelMatriculaTela_Financeiro);
        jLabelMatriculaTela_Financeiro.setBounds(10, 180, 100, 21);

        jTextFieldMatriculaTela_Financeiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldMatriculaTela_Financeiro);
        jTextFieldMatriculaTela_Financeiro.setBounds(90, 170, 230, 30);

        jTextFieldNomeTela_Financeiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldNomeTela_Financeiro);
        jTextFieldNomeTela_Financeiro.setBounds(90, 210, 430, 30);

        jTextFieldEmailTela_Financeiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldEmailTela_Financeiro);
        jTextFieldEmailTela_Financeiro.setBounds(90, 250, 430, 30);

        jTextFieldTelefoneTela_Financeiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldTelefoneTela_Financeiro.setText("(  )");
        getContentPane().add(jTextFieldTelefoneTela_Financeiro);
        jTextFieldTelefoneTela_Financeiro.setBounds(90, 290, 230, 30);

        jTextFieldEnviarTela_Financeiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldEnviarTela_Financeiro);
        jTextFieldEnviarTela_Financeiro.setBounds(90, 330, 430, 80);

        jButtonEnviarTela_Financeiro.setBackground(new java.awt.Color(0, 204, 204));
        jButtonEnviarTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonEnviarTela_Financeiro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEnviarTela_Financeiro.setText("Enviar");
        jButtonEnviarTela_Financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarTela_FinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviarTela_Financeiro);
        jButtonEnviarTela_Financeiro.setBounds(90, 420, 82, 31);

        jButtonEditarTela_Financeiro.setBackground(new java.awt.Color(0, 204, 204));
        jButtonEditarTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonEditarTela_Financeiro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditarTela_Financeiro.setText("Editar");
        getContentPane().add(jButtonEditarTela_Financeiro);
        jButtonEditarTela_Financeiro.setBounds(260, 420, 80, 31);

        jButtonSairTela_Financeiro.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSairTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonSairTela_Financeiro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSairTela_Financeiro.setText("Sair");
        jButtonSairTela_Financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairTela_FinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairTela_Financeiro);
        jButtonSairTela_Financeiro.setBounds(530, 100, 64, 31);

        jButtonVoltarDaTelaFinanceiro.setBackground(new java.awt.Color(0, 204, 204));
        jButtonVoltarDaTelaFinanceiro.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonVoltarDaTelaFinanceiro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVoltarDaTelaFinanceiro.setText("Voltar");
        jButtonVoltarDaTelaFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonVoltarDaTelaFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarDaTelaFinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarDaTelaFinanceiro);
        jButtonVoltarDaTelaFinanceiro.setBounds(440, 420, 80, 28);

        jLabelNomeTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelNomeTela_Financeiro.setForeground(new java.awt.Color(204, 255, 204));
        jLabelNomeTela_Financeiro.setText("Nome:");
        getContentPane().add(jLabelNomeTela_Financeiro);
        jLabelNomeTela_Financeiro.setBounds(10, 220, 60, 21);

        jLabelEmailTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelEmailTela_Financeiro.setForeground(new java.awt.Color(204, 255, 204));
        jLabelEmailTela_Financeiro.setText("Email:");
        getContentPane().add(jLabelEmailTela_Financeiro);
        jLabelEmailTela_Financeiro.setBounds(10, 260, 70, 21);

        jLabelTelefoneTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelTelefoneTela_Financeiro.setForeground(new java.awt.Color(204, 255, 204));
        jLabelTelefoneTela_Financeiro.setText("Telefone:");
        getContentPane().add(jLabelTelefoneTela_Financeiro);
        jLabelTelefoneTela_Financeiro.setBounds(10, 300, 90, 21);

        jLabelAssuntoTela_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelAssuntoTela_Financeiro.setForeground(new java.awt.Color(204, 255, 204));
        jLabelAssuntoTela_Financeiro.setText("Assunto:");
        getContentPane().add(jLabelAssuntoTela_Financeiro);
        jLabelAssuntoTela_Financeiro.setBounds(10, 330, 110, 21);

        jLabelFundoTela_Financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo Telas1.png"))); // NOI18N
        getContentPane().add(jLabelFundoTela_Financeiro);
        jLabelFundoTela_Financeiro.setBounds(0, 50, 600, 460);

        setSize(new java.awt.Dimension(614, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairTela_FinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairTela_FinanceiroActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButtonSairTela_FinanceiroActionPerformed

    private void jButtonVoltarDaTelaFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarDaTelaFinanceiroActionPerformed
        TelaInicio tela = new TelaInicio();
         tela.setVisible(true);
         dispose ();
    }//GEN-LAST:event_jButtonVoltarDaTelaFinanceiroActionPerformed

    private void jButtonEnviarTela_FinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarTela_FinanceiroActionPerformed
       JOptionPane.showMessageDialog(this, "ENVIADO COM SUCESSO!  VOCÊ RECBERÁ A RESPOSTA EM SEU EMAIL: ''AGUARDE''!");
       TelaFinanceiro tela = new TelaFinanceiro ();
       tela.setVisible(true);
       dispose();
       
    }//GEN-LAST:event_jButtonEnviarTela_FinanceiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel FundoTopoTela_Financeiro;
    javax.swing.JButton jButtonEditarTela_Financeiro;
    javax.swing.JButton jButtonEnviarTela_Financeiro;
    javax.swing.JButton jButtonSairTela_Financeiro;
    javax.swing.JButton jButtonVoltarDaTelaFinanceiro;
    javax.swing.JLabel jLabelAssuntoTela_Financeiro;
    javax.swing.JLabel jLabelEmailTela_Financeiro;
    javax.swing.JLabel jLabelFundoTela_Financeiro;
    javax.swing.JLabel jLabelInformeTela_Financieiro;
    javax.swing.JLabel jLabelLogoTela_Financeiro;
    javax.swing.JLabel jLabelMatriculaTela_Financeiro;
    javax.swing.JLabel jLabelNomeTela_Financeiro;
    javax.swing.JLabel jLabelTelefoneTela_Financeiro;
    javax.swing.JLabel jLabelTopoTela_Financeiro;
    javax.swing.JTextField jTextFieldEmailTela_Financeiro;
    javax.swing.JTextField jTextFieldEnviarTela_Financeiro;
    javax.swing.JTextField jTextFieldMatriculaTela_Financeiro;
    javax.swing.JTextField jTextFieldNomeTela_Financeiro;
    javax.swing.JTextField jTextFieldTelefoneTela_Financeiro;
    // End of variables declaration//GEN-END:variables
}
