/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import javax.swing.JOptionPane;

/**
 *
 * @author sistemas
 */
public class Tela_CursosPresenciais extends javax.swing.JFrame {

    /**
     * Creates new form Tela_CursosPresenciais
     */
    public Tela_CursosPresenciais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldMatriculaTelaCursosPresenciais = new javax.swing.JTextField();
        jTextFieldNomeTelaCursosPresenciais = new javax.swing.JTextField();
        jTextFieldEmailTelaCursosPresenciais = new javax.swing.JTextField();
        jTextFieldTelefoneTelaCursosPresenciais = new javax.swing.JTextField();
        jTextFieldAssuntoTelaCursosPresenciais = new javax.swing.JTextField();
        jButtonSalvarTelaCursosPresenciais = new javax.swing.JButton();
        jButtonEditarTelaCursosPresenciais = new javax.swing.JButton();
        jButtonVoltarTelaCursosPresenciais = new javax.swing.JButton();
        jButtonSairTelaCursosPresenciais = new javax.swing.JButton();
        jLabelAssuntoTelaCursosPresenciais = new javax.swing.JLabel();
        jLabelTelefoneTelaCursosPresenciais = new javax.swing.JLabel();
        jLabelEmailTelaCursosPresenciais = new javax.swing.JLabel();
        jLabelNomeTelaCursosPresenciais = new javax.swing.JLabel();
        jLabelMatriculaTelaCursosPresenciais = new javax.swing.JLabel();
        jLabelInformeTelaCursosPresenciais = new javax.swing.JLabel();
        jLabelInformeTopoTelaCursosPresenciais = new javax.swing.JLabel();
        jLabelLogoTelaCursosPresenciais = new javax.swing.JLabel();
        jLabelFundoTopoTelaCursosPresenciais = new javax.swing.JLabel();
        FundoTelaCursosPresenciais = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextFieldMatriculaTelaCursosPresenciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaTelaCursosPresenciaisActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMatriculaTelaCursosPresenciais);
        jTextFieldMatriculaTelaCursosPresenciais.setBounds(110, 160, 210, 30);
        getContentPane().add(jTextFieldNomeTelaCursosPresenciais);
        jTextFieldNomeTelaCursosPresenciais.setBounds(110, 200, 420, 30);
        getContentPane().add(jTextFieldEmailTelaCursosPresenciais);
        jTextFieldEmailTelaCursosPresenciais.setBounds(110, 240, 420, 30);

        jTextFieldTelefoneTelaCursosPresenciais.setText("(  )");
        getContentPane().add(jTextFieldTelefoneTelaCursosPresenciais);
        jTextFieldTelefoneTelaCursosPresenciais.setBounds(110, 280, 210, 30);
        getContentPane().add(jTextFieldAssuntoTelaCursosPresenciais);
        jTextFieldAssuntoTelaCursosPresenciais.setBounds(110, 320, 420, 90);

        jButtonSalvarTelaCursosPresenciais.setBackground(new java.awt.Color(0, 255, 255));
        jButtonSalvarTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSalvarTelaCursosPresenciais.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarTelaCursosPresenciais.setText("Salvar");
        jButtonSalvarTelaCursosPresenciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarTelaCursosPresenciaisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarTelaCursosPresenciais);
        jButtonSalvarTelaCursosPresenciais.setBounds(110, 420, 80, 28);

        jButtonEditarTelaCursosPresenciais.setBackground(new java.awt.Color(0, 204, 204));
        jButtonEditarTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonEditarTelaCursosPresenciais.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditarTelaCursosPresenciais.setText("Editar");
        getContentPane().add(jButtonEditarTelaCursosPresenciais);
        jButtonEditarTelaCursosPresenciais.setBounds(280, 420, 90, 28);

        jButtonVoltarTelaCursosPresenciais.setBackground(new java.awt.Color(0, 204, 204));
        jButtonVoltarTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonVoltarTelaCursosPresenciais.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVoltarTelaCursosPresenciais.setText("Voltar");
        jButtonVoltarTelaCursosPresenciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarTelaCursosPresenciaisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarTelaCursosPresenciais);
        jButtonVoltarTelaCursosPresenciais.setBounds(450, 420, 80, 28);

        jButtonSairTelaCursosPresenciais.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSairTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSairTelaCursosPresenciais.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSairTelaCursosPresenciais.setText("Sair");
        jButtonSairTelaCursosPresenciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairTelaCursosPresenciaisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairTelaCursosPresenciais);
        jButtonSairTelaCursosPresenciais.setBounds(530, 100, 70, 28);

        jLabelAssuntoTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelAssuntoTelaCursosPresenciais.setForeground(new java.awt.Color(204, 255, 204));
        jLabelAssuntoTelaCursosPresenciais.setText("ASSUNTO:");
        getContentPane().add(jLabelAssuntoTelaCursosPresenciais);
        jLabelAssuntoTelaCursosPresenciais.setBounds(10, 330, 110, 20);

        jLabelTelefoneTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelTelefoneTelaCursosPresenciais.setForeground(new java.awt.Color(204, 255, 204));
        jLabelTelefoneTelaCursosPresenciais.setText("TELEFONE:");
        getContentPane().add(jLabelTelefoneTelaCursosPresenciais);
        jLabelTelefoneTelaCursosPresenciais.setBounds(10, 290, 90, 21);

        jLabelEmailTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelEmailTelaCursosPresenciais.setForeground(new java.awt.Color(204, 255, 204));
        jLabelEmailTelaCursosPresenciais.setText("EMAIL:");
        getContentPane().add(jLabelEmailTelaCursosPresenciais);
        jLabelEmailTelaCursosPresenciais.setBounds(10, 250, 60, 21);

        jLabelNomeTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelNomeTelaCursosPresenciais.setForeground(new java.awt.Color(204, 255, 204));
        jLabelNomeTelaCursosPresenciais.setText("NOME:");
        getContentPane().add(jLabelNomeTelaCursosPresenciais);
        jLabelNomeTelaCursosPresenciais.setBounds(10, 210, 70, 21);

        jLabelMatriculaTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelMatriculaTelaCursosPresenciais.setForeground(new java.awt.Color(204, 255, 204));
        jLabelMatriculaTelaCursosPresenciais.setText("MATRÍCULA:");
        getContentPane().add(jLabelMatriculaTelaCursosPresenciais);
        jLabelMatriculaTelaCursosPresenciais.setBounds(10, 170, 120, 21);

        jLabelInformeTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelInformeTelaCursosPresenciais.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInformeTelaCursosPresenciais.setText("PREENCHA O FORMULÁRIO E ENVIE!");
        getContentPane().add(jLabelInformeTelaCursosPresenciais);
        jLabelInformeTelaCursosPresenciais.setBounds(80, 110, 370, 30);

        jLabelInformeTopoTelaCursosPresenciais.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelInformeTopoTelaCursosPresenciais.setForeground(new java.awt.Color(0, 255, 255));
        jLabelInformeTopoTelaCursosPresenciais.setText("PRESENCIAIS");
        getContentPane().add(jLabelInformeTopoTelaCursosPresenciais);
        jLabelInformeTopoTelaCursosPresenciais.setBounds(320, 20, 310, 52);

        jLabelLogoTelaCursosPresenciais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PRESENCIAL.png"))); // NOI18N
        getContentPane().add(jLabelLogoTelaCursosPresenciais);
        jLabelLogoTelaCursosPresenciais.setBounds(0, 0, 90, 80);

        jLabelFundoTopoTelaCursosPresenciais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Topo de telas.png"))); // NOI18N
        getContentPane().add(jLabelFundoTopoTelaCursosPresenciais);
        jLabelFundoTopoTelaCursosPresenciais.setBounds(0, 0, 600, 100);

        FundoTelaCursosPresenciais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo Telas1.png"))); // NOI18N
        getContentPane().add(FundoTelaCursosPresenciais);
        FundoTelaCursosPresenciais.setBounds(0, -50, 600, 650);

        setSize(new java.awt.Dimension(616, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairTelaCursosPresenciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairTelaCursosPresenciaisActionPerformed
       System.exit(0);
       
    }//GEN-LAST:event_jButtonSairTelaCursosPresenciaisActionPerformed

    private void jButtonVoltarTelaCursosPresenciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarTelaCursosPresenciaisActionPerformed
        TelaInicio tela = new TelaInicio();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarTelaCursosPresenciaisActionPerformed

    private void jTextFieldMatriculaTelaCursosPresenciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaTelaCursosPresenciaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaTelaCursosPresenciaisActionPerformed

    private void jButtonSalvarTelaCursosPresenciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarTelaCursosPresenciaisActionPerformed
        JOptionPane.showMessageDialog(this, "ENVIADO COM SUCESSO!  VOCÊ RECBERÁ A RESPOSTA EM SEU EMAIL: ''AGUARDE''!");
       Tela_CursosPresenciais tela = new Tela_CursosPresenciais ();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonSalvarTelaCursosPresenciaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_CursosPresenciais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_CursosPresenciais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_CursosPresenciais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_CursosPresenciais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_CursosPresenciais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel FundoTelaCursosPresenciais;
    javax.swing.JButton jButtonEditarTelaCursosPresenciais;
    javax.swing.JButton jButtonSairTelaCursosPresenciais;
    javax.swing.JButton jButtonSalvarTelaCursosPresenciais;
    javax.swing.JButton jButtonVoltarTelaCursosPresenciais;
    javax.swing.JLabel jLabelAssuntoTelaCursosPresenciais;
    javax.swing.JLabel jLabelEmailTelaCursosPresenciais;
    javax.swing.JLabel jLabelFundoTopoTelaCursosPresenciais;
    javax.swing.JLabel jLabelInformeTelaCursosPresenciais;
    javax.swing.JLabel jLabelInformeTopoTelaCursosPresenciais;
    javax.swing.JLabel jLabelLogoTelaCursosPresenciais;
    javax.swing.JLabel jLabelMatriculaTelaCursosPresenciais;
    javax.swing.JLabel jLabelNomeTelaCursosPresenciais;
    javax.swing.JLabel jLabelTelefoneTelaCursosPresenciais;
    javax.swing.JTextField jTextFieldAssuntoTelaCursosPresenciais;
    javax.swing.JTextField jTextFieldEmailTelaCursosPresenciais;
    javax.swing.JTextField jTextFieldMatriculaTelaCursosPresenciais;
    javax.swing.JTextField jTextFieldNomeTelaCursosPresenciais;
    javax.swing.JTextField jTextFieldTelefoneTelaCursosPresenciais;
    // End of variables declaration//GEN-END:variables
}
