/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import CentralConexões.ConnectionFactory;

/**
 *
 * @author sistemas
 */
public class TelaInicio extends javax.swing.JFrame {

    
    ConnectionFactory conectar = new ConnectionFactory();
    
    public TelaInicio() {
        initComponents();
        conectar.getConnection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCliqueAtendimento = new javax.swing.JLabel();
        jButtonFinanceiro = new javax.swing.JButton();
        jLabelDrsc_Financeiro = new javax.swing.JLabel();
        jButtonEadFlex = new javax.swing.JButton();
        jLabelDesc_EadFlex = new javax.swing.JLabel();
        jButtonC_Presenciais = new javax.swing.JButton();
        jLabelDesc_Presencial = new javax.swing.JLabel();
        jLabelContEadFlex = new javax.swing.JLabel();
        jLabelContPresencial = new javax.swing.JLabel();
        jButtonGuiaConsulta = new javax.swing.JButton();
        jLabelDesc_GuiaConsulta = new javax.swing.JLabel();
        jLabelContGuiaConsulta = new javax.swing.JLabel();
        jButtonTelaInicioSair = new javax.swing.JButton();
        jLabelBemVindo = new javax.swing.JLabel();
        jLabelLogoTelaInicio = new javax.swing.JLabel();
        jLabelFundoTelaTopo_Inicio = new javax.swing.JLabel();
        jLabelFundoTelaInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelCliqueAtendimento.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelCliqueAtendimento.setForeground(new java.awt.Color(0, 204, 204));
        jLabelCliqueAtendimento.setText("CLIQUE NA OPÇÃO QUE DESEJA ATENDIMENTO!");
        getContentPane().add(jLabelCliqueAtendimento);
        jLabelCliqueAtendimento.setBounds(50, 90, 560, 40);

        jButtonFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Figura2.png"))); // NOI18N
        jButtonFinanceiro.setToolTipText("Financeiro ");
        jButtonFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinanceiro);
        jButtonFinanceiro.setBounds(30, 150, 90, 110);

        jLabelDrsc_Financeiro.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabelDrsc_Financeiro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDrsc_Financeiro.setText("FINANCEIRO");
        getContentPane().add(jLabelDrsc_Financeiro);
        jLabelDrsc_Financeiro.setBounds(40, 280, 100, 30);

        jButtonEadFlex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/eadflex.png"))); // NOI18N
        jButtonEadFlex.setToolTipText("Cursos EAD/Flex");
        jButtonEadFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEadFlexActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEadFlex);
        jButtonEadFlex.setBounds(170, 150, 90, 110);

        jLabelDesc_EadFlex.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabelDesc_EadFlex.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesc_EadFlex.setText("CURSOS ");
        getContentPane().add(jLabelDesc_EadFlex);
        jLabelDesc_EadFlex.setBounds(190, 280, 70, 18);

        jButtonC_Presenciais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PRESENCIAL.png"))); // NOI18N
        jButtonC_Presenciais.setToolTipText("Cursos Presenciais");
        jButtonC_Presenciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC_PresenciaisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonC_Presenciais);
        jButtonC_Presenciais.setBounds(310, 150, 90, 110);

        jLabelDesc_Presencial.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabelDesc_Presencial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesc_Presencial.setText("CURSOS ");
        getContentPane().add(jLabelDesc_Presencial);
        jLabelDesc_Presencial.setBounds(330, 270, 60, 20);

        jLabelContEadFlex.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabelContEadFlex.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContEadFlex.setText("EAD/FLEX");
        getContentPane().add(jLabelContEadFlex);
        jLabelContEadFlex.setBounds(190, 300, 60, 15);

        jLabelContPresencial.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabelContPresencial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContPresencial.setText("PRESENCIAIS");
        getContentPane().add(jLabelContPresencial);
        jLabelContPresencial.setBounds(320, 300, 90, 15);

        jButtonGuiaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Guia.png"))); // NOI18N
        jButtonGuiaConsulta.setToolTipText("Guia para Acessos");
        jButtonGuiaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuiaConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuiaConsulta);
        jButtonGuiaConsulta.setBounds(450, 150, 90, 109);

        jLabelDesc_GuiaConsulta.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabelDesc_GuiaConsulta.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDesc_GuiaConsulta.setText("GUIA");
        getContentPane().add(jLabelDesc_GuiaConsulta);
        jLabelDesc_GuiaConsulta.setBounds(480, 270, 28, 30);

        jLabelContGuiaConsulta.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabelContGuiaConsulta.setForeground(new java.awt.Color(255, 0, 0));
        jLabelContGuiaConsulta.setText("DE CONSULTA");
        getContentPane().add(jLabelContGuiaConsulta);
        jLabelContGuiaConsulta.setBounds(460, 300, 100, 15);

        jButtonTelaInicioSair.setBackground(new java.awt.Color(51, 255, 255));
        jButtonTelaInicioSair.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonTelaInicioSair.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTelaInicioSair.setText("Sair");
        jButtonTelaInicioSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaInicioSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTelaInicioSair);
        jButtonTelaInicioSair.setBounds(250, 390, 73, 25);

        jLabelBemVindo.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabelBemVindo.setForeground(new java.awt.Color(51, 255, 255));
        jLabelBemVindo.setText("Seja Bem Vindo!");
        getContentPane().add(jLabelBemVindo);
        jLabelBemVindo.setBounds(450, 0, 150, 60);

        jLabelLogoTelaInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.jpg"))); // NOI18N
        getContentPane().add(jLabelLogoTelaInicio);
        jLabelLogoTelaInicio.setBounds(10, 0, 280, 90);

        jLabelFundoTelaTopo_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Topo de telas.png"))); // NOI18N
        getContentPane().add(jLabelFundoTelaTopo_Inicio);
        jLabelFundoTelaTopo_Inicio.setBounds(0, 0, 600, 130);

        jLabelFundoTelaInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo Telas1.png"))); // NOI18N
        getContentPane().add(jLabelFundoTelaInicio);
        jLabelFundoTelaInicio.setBounds(0, 50, 600, 380);

        setSize(new java.awt.Dimension(616, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinanceiroActionPerformed

    TelaFinanceiro tela = new TelaFinanceiro();
         tela.setVisible(true);
         dispose ();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFinanceiroActionPerformed

    private void jButtonTelaInicioSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaInicioSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButtonTelaInicioSairActionPerformed

    private void jButtonEadFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEadFlexActionPerformed
        Tela_CursosEadFlex tela = new Tela_CursosEadFlex();
         tela.setVisible(true);
         dispose ();
    }//GEN-LAST:event_jButtonEadFlexActionPerformed

    private void jButtonC_PresenciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonC_PresenciaisActionPerformed
        Tela_CursosPresenciais tela = new Tela_CursosPresenciais();
         tela.setVisible(true);
         dispose ();
    }//GEN-LAST:event_jButtonC_PresenciaisActionPerformed

    private void jButtonGuiaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuiaConsultaActionPerformed
        Tela_GuiaAcessos tela = new Tela_GuiaAcessos();
         tela.setVisible(true);
         dispose ();
    }//GEN-LAST:event_jButtonGuiaConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonC_Presenciais;
    private javax.swing.JButton jButtonEadFlex;
    private javax.swing.JButton jButtonFinanceiro;
    private javax.swing.JButton jButtonGuiaConsulta;
    private javax.swing.JButton jButtonTelaInicioSair;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JLabel jLabelCliqueAtendimento;
    private javax.swing.JLabel jLabelContEadFlex;
    private javax.swing.JLabel jLabelContGuiaConsulta;
    private javax.swing.JLabel jLabelContPresencial;
    private javax.swing.JLabel jLabelDesc_EadFlex;
    private javax.swing.JLabel jLabelDesc_GuiaConsulta;
    private javax.swing.JLabel jLabelDesc_Presencial;
    private javax.swing.JLabel jLabelDrsc_Financeiro;
    private javax.swing.JLabel jLabelFundoTelaInicio;
    private javax.swing.JLabel jLabelFundoTelaTopo_Inicio;
    private javax.swing.JLabel jLabelLogoTelaInicio;
    // End of variables declaration//GEN-END:variables
}
