/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

/**
 *
 * @author sistemas
 */
public class Tela_GuiaAcessos extends javax.swing.JFrame {

    /**
     * Creates new form Tela_GuiaAcessos
     */
    public Tela_GuiaAcessos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jButtonProcedimentos = new javax.swing.JButton();
        jButtonTutoriaisPortalAluno = new javax.swing.JButton();
        jButtonTelefonesUteis = new javax.swing.JButton();
        jButtonOutrasInformações = new javax.swing.JButton();
        jButtonVoltarTelaGuia = new javax.swing.JButton();
        jButtonSairTelaGuia = new javax.swing.JButton();
        jLabelLogoTriagemTelaGuia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTelefonesUteis = new javax.swing.JLabel();
        jLabelTutorialPortalAluno = new javax.swing.JLabel();
        jLabelInformaçõesProcedimentos = new javax.swing.JLabel();
        jLabelInformeTopoTelaGuia = new javax.swing.JLabel();
        jLabelLogoTelaGuiaAcessos = new javax.swing.JLabel();
        jLabelFundoTelaGuiaAcessos = new javax.swing.JLabel();
        jLabelFundo2TelaGuiaAcessos = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonProcedimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Botão Guia.png"))); // NOI18N
        jButtonProcedimentos.setBorder(null);
        jButtonProcedimentos.setContentAreaFilled(false);
        getContentPane().add(jButtonProcedimentos);
        jButtonProcedimentos.setBounds(20, 130, 40, 30);

        jButtonTutoriaisPortalAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Botão Guia.png"))); // NOI18N
        jButtonTutoriaisPortalAluno.setBorderPainted(false);
        jButtonTutoriaisPortalAluno.setContentAreaFilled(false);
        getContentPane().add(jButtonTutoriaisPortalAluno);
        jButtonTutoriaisPortalAluno.setBounds(220, 300, 40, 40);

        jButtonTelefonesUteis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Botão Guia.png"))); // NOI18N
        jButtonTelefonesUteis.setBorderPainted(false);
        jButtonTelefonesUteis.setContentAreaFilled(false);
        getContentPane().add(jButtonTelefonesUteis);
        jButtonTelefonesUteis.setBounds(110, 220, 40, 30);

        jButtonOutrasInformações.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Botão Guia.png"))); // NOI18N
        jButtonOutrasInformações.setBorderPainted(false);
        jButtonOutrasInformações.setContentAreaFilled(false);
        getContentPane().add(jButtonOutrasInformações);
        jButtonOutrasInformações.setBounds(330, 380, 40, 30);

        jButtonVoltarTelaGuia.setBackground(new java.awt.Color(0, 255, 255));
        jButtonVoltarTelaGuia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonVoltarTelaGuia.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVoltarTelaGuia.setText("Voltar");
        jButtonVoltarTelaGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarTelaGuiaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarTelaGuia);
        jButtonVoltarTelaGuia.setBounds(200, 440, 80, 28);

        jButtonSairTelaGuia.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSairTelaGuia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSairTelaGuia.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSairTelaGuia.setText("Sair");
        jButtonSairTelaGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairTelaGuiaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairTelaGuia);
        jButtonSairTelaGuia.setBounds(320, 440, 80, 28);

        jLabelLogoTriagemTelaGuia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.jpg"))); // NOI18N
        getContentPane().add(jLabelLogoTriagemTelaGuia);
        jLabelLogoTriagemTelaGuia.setBounds(310, 100, 280, 80);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Outras Informações");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 390, 180, 21);

        jLabelTelefonesUteis.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelTelefonesUteis.setForeground(new java.awt.Color(0, 255, 255));
        jLabelTelefonesUteis.setText("Telefones Úteis");
        getContentPane().add(jLabelTelefonesUteis);
        jLabelTelefonesUteis.setBounds(170, 230, 190, 21);

        jLabelTutorialPortalAluno.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelTutorialPortalAluno.setForeground(new java.awt.Color(0, 255, 255));
        jLabelTutorialPortalAluno.setText("Tutoriais Portal do Aluno");
        getContentPane().add(jLabelTutorialPortalAluno);
        jLabelTutorialPortalAluno.setBounds(280, 310, 200, 21);

        jLabelInformaçõesProcedimentos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelInformaçõesProcedimentos.setForeground(new java.awt.Color(0, 255, 255));
        jLabelInformaçõesProcedimentos.setText("Procedimentos");
        getContentPane().add(jLabelInformaçõesProcedimentos);
        jLabelInformaçõesProcedimentos.setBounds(80, 140, 120, 21);

        jLabelInformeTopoTelaGuia.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelInformeTopoTelaGuia.setForeground(new java.awt.Color(0, 255, 255));
        jLabelInformeTopoTelaGuia.setText("GUIA DE CONSULTAS");
        getContentPane().add(jLabelInformeTopoTelaGuia);
        jLabelInformeTopoTelaGuia.setBounds(100, 10, 450, 40);

        jLabelLogoTelaGuiaAcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Guia.png"))); // NOI18N
        getContentPane().add(jLabelLogoTelaGuiaAcessos);
        jLabelLogoTelaGuiaAcessos.setBounds(0, -10, 80, 120);

        jLabelFundoTelaGuiaAcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo tela login.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaGuiaAcessos);
        jLabelFundoTelaGuiaAcessos.setBounds(0, 0, 600, 520);

        jLabelFundo2TelaGuiaAcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo tela3.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo2TelaGuiaAcessos);
        jLabelFundo2TelaGuiaAcessos.setBounds(0, -30, 600, 540);

        setSize(new java.awt.Dimension(615, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairTelaGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairTelaGuiaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairTelaGuiaActionPerformed

    private void jButtonVoltarTelaGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarTelaGuiaActionPerformed
        TelaInicio tela = new TelaInicio();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarTelaGuiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_GuiaAcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_GuiaAcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_GuiaAcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_GuiaAcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_GuiaAcessos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonOutrasInformações;
    javax.swing.JButton jButtonProcedimentos;
    javax.swing.JButton jButtonSairTelaGuia;
    javax.swing.JButton jButtonTelefonesUteis;
    javax.swing.JButton jButtonTutoriaisPortalAluno;
    javax.swing.JButton jButtonVoltarTelaGuia;
    javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabelFundo2TelaGuiaAcessos;
    javax.swing.JLabel jLabelFundoTelaGuiaAcessos;
    javax.swing.JLabel jLabelInformaçõesProcedimentos;
    javax.swing.JLabel jLabelInformeTopoTelaGuia;
    javax.swing.JLabel jLabelLogoTelaGuiaAcessos;
    javax.swing.JLabel jLabelLogoTriagemTelaGuia;
    javax.swing.JLabel jLabelTelefonesUteis;
    javax.swing.JLabel jLabelTutorialPortalAluno;
    // End of variables declaration//GEN-END:variables
}
