/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import javax.swing.JOptionPane;

/**
 *
 * @author sistemas
 */
public class Tela_CursosEadFlex extends javax.swing.JFrame {

    /**
     * Creates new form Tela_CursosEadFlex
     */
    public Tela_CursosEadFlex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNomeTelaEadFlex = new javax.swing.JTextField();
        jTextFieldMatriculaTelaEadFlex = new javax.swing.JTextField();
        jTextFieldEmailTelaEadFlex = new javax.swing.JTextField();
        jTextFieldTelefoneTelaEadFlex = new javax.swing.JTextField();
        jTextFieldAssuntoTelaEadFlex = new javax.swing.JTextField();
        jButtonSalvarTelaEadFlex = new javax.swing.JButton();
        jButtonEditarTelaEadFlex = new javax.swing.JButton();
        jButtonVoltarTelaEadFlex = new javax.swing.JButton();
        jButtonSairTelaEadFlex = new javax.swing.JButton();
        jLabelAssuntoTelaEadFlex = new javax.swing.JLabel();
        jLabelTelefoneTelaEadFlex = new javax.swing.JLabel();
        jLabelEmailTelaEadFlex = new javax.swing.JLabel();
        jLabelMatriculaTelaEadFlex = new javax.swing.JLabel();
        jLabelNomeTelaEadFlex = new javax.swing.JLabel();
        jLabelinformeEadFlex = new javax.swing.JLabel();
        jLabelInformeTopoTela_EadFlex = new javax.swing.JLabel();
        jLabelLogoEadFlex = new javax.swing.JLabel();
        jLabelTopoTela_EadFlex = new javax.swing.JLabel();
        jLabelFundoTela_EadFlex = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextFieldNomeTelaEadFlex);
        jTextFieldNomeTelaEadFlex.setBounds(110, 200, 420, 30);
        getContentPane().add(jTextFieldMatriculaTelaEadFlex);
        jTextFieldMatriculaTelaEadFlex.setBounds(110, 160, 210, 30);
        getContentPane().add(jTextFieldEmailTelaEadFlex);
        jTextFieldEmailTelaEadFlex.setBounds(110, 240, 420, 30);

        jTextFieldTelefoneTelaEadFlex.setText("(  )");
        getContentPane().add(jTextFieldTelefoneTelaEadFlex);
        jTextFieldTelefoneTelaEadFlex.setBounds(110, 280, 210, 30);
        getContentPane().add(jTextFieldAssuntoTelaEadFlex);
        jTextFieldAssuntoTelaEadFlex.setBounds(110, 320, 420, 90);

        jButtonSalvarTelaEadFlex.setBackground(new java.awt.Color(0, 255, 255));
        jButtonSalvarTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSalvarTelaEadFlex.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarTelaEadFlex.setText("Salvar");
        jButtonSalvarTelaEadFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarTelaEadFlexActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarTelaEadFlex);
        jButtonSalvarTelaEadFlex.setBounds(110, 420, 80, 28);

        jButtonEditarTelaEadFlex.setBackground(new java.awt.Color(0, 255, 255));
        jButtonEditarTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonEditarTelaEadFlex.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditarTelaEadFlex.setText("Editar");
        getContentPane().add(jButtonEditarTelaEadFlex);
        jButtonEditarTelaEadFlex.setBounds(280, 420, 90, 28);

        jButtonVoltarTelaEadFlex.setBackground(new java.awt.Color(0, 255, 255));
        jButtonVoltarTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonVoltarTelaEadFlex.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVoltarTelaEadFlex.setText("Voltar");
        jButtonVoltarTelaEadFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarTelaEadFlexActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarTelaEadFlex);
        jButtonVoltarTelaEadFlex.setBounds(450, 420, 80, 28);

        jButtonSairTelaEadFlex.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSairTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSairTelaEadFlex.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSairTelaEadFlex.setText("Sair");
        jButtonSairTelaEadFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairTelaEadFlexActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairTelaEadFlex);
        jButtonSairTelaEadFlex.setBounds(540, 100, 60, 30);

        jLabelAssuntoTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelAssuntoTelaEadFlex.setForeground(new java.awt.Color(204, 255, 204));
        jLabelAssuntoTelaEadFlex.setText("ASSUNTO:");
        getContentPane().add(jLabelAssuntoTelaEadFlex);
        jLabelAssuntoTelaEadFlex.setBounds(10, 330, 120, 21);

        jLabelTelefoneTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelTelefoneTelaEadFlex.setForeground(new java.awt.Color(204, 255, 204));
        jLabelTelefoneTelaEadFlex.setText("TELEFONE:");
        getContentPane().add(jLabelTelefoneTelaEadFlex);
        jLabelTelefoneTelaEadFlex.setBounds(10, 290, 87, 21);

        jLabelEmailTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelEmailTelaEadFlex.setForeground(new java.awt.Color(204, 255, 204));
        jLabelEmailTelaEadFlex.setText("EMAIL:");
        getContentPane().add(jLabelEmailTelaEadFlex);
        jLabelEmailTelaEadFlex.setBounds(10, 250, 53, 21);

        jLabelMatriculaTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelMatriculaTelaEadFlex.setForeground(new java.awt.Color(204, 255, 204));
        jLabelMatriculaTelaEadFlex.setText("MATRÍCULA:");
        getContentPane().add(jLabelMatriculaTelaEadFlex);
        jLabelMatriculaTelaEadFlex.setBounds(10, 170, 100, 21);

        jLabelNomeTelaEadFlex.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelNomeTelaEadFlex.setForeground(new java.awt.Color(204, 255, 204));
        jLabelNomeTelaEadFlex.setText("NOME:");
        getContentPane().add(jLabelNomeTelaEadFlex);
        jLabelNomeTelaEadFlex.setBounds(10, 210, 90, 21);

        jLabelinformeEadFlex.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelinformeEadFlex.setForeground(new java.awt.Color(0, 0, 0));
        jLabelinformeEadFlex.setText("PREENCHA O FORMULÁRIO E ENVIE!");
        getContentPane().add(jLabelinformeEadFlex);
        jLabelinformeEadFlex.setBounds(80, 110, 380, 30);

        jLabelInformeTopoTela_EadFlex.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelInformeTopoTela_EadFlex.setForeground(new java.awt.Color(0, 204, 204));
        jLabelInformeTopoTela_EadFlex.setText("EAD/FLEX");
        getContentPane().add(jLabelInformeTopoTela_EadFlex);
        jLabelInformeTopoTela_EadFlex.setBounds(400, 10, 220, 70);

        jLabelLogoEadFlex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/eadflex.png"))); // NOI18N
        getContentPane().add(jLabelLogoEadFlex);
        jLabelLogoEadFlex.setBounds(0, 0, 80, 80);

        jLabelTopoTela_EadFlex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Topo de telas.png"))); // NOI18N
        getContentPane().add(jLabelTopoTela_EadFlex);
        jLabelTopoTela_EadFlex.setBounds(0, 0, 600, 100);

        jLabelFundoTela_EadFlex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo Telas1.png"))); // NOI18N
        getContentPane().add(jLabelFundoTela_EadFlex);
        jLabelFundoTela_EadFlex.setBounds(0, 0, 600, 540);

        setSize(new java.awt.Dimension(616, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairTelaEadFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairTelaEadFlexActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairTelaEadFlexActionPerformed

    private void jButtonVoltarTelaEadFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarTelaEadFlexActionPerformed
        TelaInicio tela = new TelaInicio();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarTelaEadFlexActionPerformed

    private void jButtonSalvarTelaEadFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarTelaEadFlexActionPerformed
        JOptionPane.showMessageDialog(this, "ENVIADO COM SUCESSO!  VOCÊ RECBERÁ A RESPOSTA EM SEU EMAIL: ''AGUARDE''!");
       Tela_CursosEadFlex tela = new Tela_CursosEadFlex ();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonSalvarTelaEadFlexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_CursosEadFlex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_CursosEadFlex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_CursosEadFlex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_CursosEadFlex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_CursosEadFlex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonEditarTelaEadFlex;
    javax.swing.JButton jButtonSairTelaEadFlex;
    javax.swing.JButton jButtonSalvarTelaEadFlex;
    javax.swing.JButton jButtonVoltarTelaEadFlex;
    javax.swing.JLabel jLabelAssuntoTelaEadFlex;
    javax.swing.JLabel jLabelEmailTelaEadFlex;
    javax.swing.JLabel jLabelFundoTela_EadFlex;
    javax.swing.JLabel jLabelInformeTopoTela_EadFlex;
    javax.swing.JLabel jLabelLogoEadFlex;
    javax.swing.JLabel jLabelMatriculaTelaEadFlex;
    javax.swing.JLabel jLabelNomeTelaEadFlex;
    javax.swing.JLabel jLabelTelefoneTelaEadFlex;
    javax.swing.JLabel jLabelTopoTela_EadFlex;
    javax.swing.JLabel jLabelinformeEadFlex;
    javax.swing.JTextField jTextFieldAssuntoTelaEadFlex;
    javax.swing.JTextField jTextFieldEmailTelaEadFlex;
    javax.swing.JTextField jTextFieldMatriculaTelaEadFlex;
    javax.swing.JTextField jTextFieldNomeTelaEadFlex;
    javax.swing.JTextField jTextFieldTelefoneTelaEadFlex;
    // End of variables declaration//GEN-END:variables
}
